CREATE DATABASE IF NOT EXISTS adamas_db;

USE adamas_db;

CREATE TABLE IF NOT EXISTS INSTITUTION_USER (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  cnpj CHAR(14) NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS EVENT (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  address VARCHAR(255) NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS OWNER_EVENT (
  event_id INT NOT NULL,
  owner_id INT NOT NULL,
  PRIMARY KEY (event_id, owner_id),
  FOREIGN KEY (event_id) REFERENCES EVENT(id) ON DELETE CASCADE,
  FOREIGN KEY (owner_id) REFERENCES INSTITUTION_USER(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ROOM_IN_EVENT (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  event_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  FOREIGN KEY (event_id) REFERENCES EVENT(id) ON DELETE CASCADE
);

-- Instituição administradora padrão
-- Email: admin@adamas.com | Senha: admin123
INSERT INTO INSTITUTION_USER (name, email, password, cnpj, is_admin)
VALUES ('Admin', 'admin@adamas.com', '$2b$10$z5J2wmMW1CHVGlk4nuW9YO29r0lVYjwGWEBDL/xHfPl1Eo5I4301a', '00000000000000', TRUE)
ON DUPLICATE KEY UPDATE is_admin = TRUE;
